### ISSUE TITLE
China csv files

### ISSUE THREAD

**Issue by pinkfloydisch** [jiyingz/COVID19_projections#1]
Hi, Thanks for your nice codes.
may I ask you please share the link of NHC that you get the files for China ? because I couldn't find them there.

Best regards,
Nik

**Comment by jiyingz** [comment]
Hi Nik, 

I got the China NHC data from here: http://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm#Beijing%20Municipality%20Update
The website is updated daily, my data will be updated occasionally (roughly weekly up until mid-June).

Hope this helps!

**Comment by jiyingz** [comment]
Hi Nik,

I got the China NHC data from here:
http://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm#Beijing%20Municipality%20Update
The website is updated daily, my data will be updated occasionally (roughly
weekly up until mid-June).

Hope this helps!

Cheers,
~Jiying
